set prog "argc"
set test "argc no args"
spawn ./$prog 1
expect eof
lassign [wait] pid spawnid os_error_flag value
if {$os_error_flag == 0} {
  if {$value == 0} {
    send_user "$test PASS\n"
    pass "$test"
  } else {
    send_user "$test FAIL (Wrong value returned)\n"
    fail "$test"
  }
} else {
  send_user "$test FAIL (OS error)\n"
  fail "$test"
}
set test "argc 2 args"
spawn ./$prog 1 2
expect eof
lassign [wait] pid spawnid os_error_flag value
if {$os_error_flag == 0} {
  if {$value == 1} {
    send_user "$test PASS\n"
    pass "$test"
  } else {
    send_user "$test FAIL (Wrong value returned)\n"
    fail "$test"
  }
} else {
  send_user "$test FAIL (OS error)\n"
  fail "$test"
}
